### ISSUE TITLE
Do we really need to run dials.report and dials.predict after every step?

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI2#16]
Some of them it is impossible - e.g. import - others it is unlikely to be insightful and usually people (i.e. users) would run it once at the end to generate all the reports at once. 

Alternative: run the report of the report panel is opened and there is no report as yet. 

For substantial data sets this can be very costly to run many times. 

Also: no need to run `dials.predict` at the end of the integration step as we have literally got a reflection file with all the predictions in which was used for the integration, called `integrated.refl`

**Comment by luisodls** [comment]
![console_wO_predict](https://user-images.githubusercontent.com/14178049/194108011-16e1fabc-bcd4-427b-8aef-498bc4e19371.png)

Now it runs both predict and report in background in a way that it does **_not_** blocks execution or control of _any_ step

**Comment by graeme-winter** [comment]
Running in background is different to not running

If the report is expensive, or prediction, my computer may still be useless until it is complete

Please, can we make this actually optional?

**Comment by luisodls** [comment]
I can automatically tick some steps like: import, generate mask, refine bravais settings ...
Do you want me to?

**Comment by dagewa** [comment]
Personally, I really don't like the idea of an additional tick box bogging down the user interface. I think DUI2 should be clever here. Don't run the steps when they are not useful (report after import, predict after integrate, etc.). Otherwise, _do_ run them, but in the background in a non-blocking way (which I think has already been done). If the user clicks on the report tab before a report is ready, DUI should say "report not ready" or something. Likewise, clicking on the image view before predictions are ready should show the images without delay, then the predictions should appear when they are ready.

Also, DUI2 should never re-run report or prediction steps when navigating the tree. If they were run once, they should be available for immediate display. Maybe this is how it already is, but I'm just checking to be sure.

I don't know if there are circumstances when running a report or predictions in a single subprocess is so expensive that the computer is useless until complete. If that's the case, we probably have worse problems than I thought.

**Comment by graeme-winter** [comment]
> I don't know if there are circumstances when running a report or predictions in a single subprocess is so expensive that the computer is useless until complete. If that's the case, we probably have worse problems than I thought.

If the size of your data set is sufficient that it is approaching the total resource on the computer, _also_ running report can be problematic. In this case, for instant, I may only want a report at the very end (which implicitly generates all the intermediate report results)

**Comment by luisodls** [comment]
At the moment Dui2 does what @dagewa assumes, runs predictions and report in background without blocking anything at all, and as soon as either report or predictions are ready it shows it. I have not seen it the case where as @graeme-winter says it gets problematic. But if that is the case, I don't mind giving the option to the user and automatically ticking by default in a clever way, the only disadvantage here is that as @dagewa said the check box takes room in the gui and novice users may not now what to do with. Maybe wit a tool-tip we can make it more explicit.

**Comment by luisodls** [comment]
There is a way to avoid taking extra room for the check box, it will be next to the << reset to default >> button, that space is already taken. It will only look more dense, but will not take extra room.

**Comment by luisodls** [comment]
Done

**Comment by luisodls** [comment]
adding a screenshot for clarity 

![Screenshot_tick_predict_n_report](https://user-images.githubusercontent.com/14178049/194942474-4d6ca1ae-e413-4335-b46b-9b2f589642c9.png)

**Comment by luisodls** [comment]
is automatically not checked in nodes like: `import, refine_bravais_settings, generate_mask, apply_mask, export`.

**Comment by dagewa** [comment]
I'm happy with this if @graeme-winter is happy
